version: '3'

services:
  buddies-express-be:
    container_name: buddies-express-be
    image: express-be:latest
    restart: always
    ports:
      - 7100:3000
    logging:
      driver: "json-file"
      options:
        max-size: "300m" 
        max-file: "5"
    volumes:
      - ./logs:/var/log/app