name: Deploy Express.js to Production (Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: iqbal
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
            touch .env
            echo "${{secrets.PROD_ENV}}" >> .env

      - name: Build Docker Image
        run: |
          docker build -t express-be:latest -f stage/dev-stage/Dockerfile .

  deploy:
    runs-on: iqbal
    needs: build 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop & Remove Existing Containers
        run: |
          docker compose -f stage/prod-stage/prod.yaml down || true

      - name: Deploy New Containers
        run: |
          docker compose -f stage/prod-stage/prod.yaml up -d
